FROM node:latest

WORKDIR './app'

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json .

COPY package-lock.json .

RUN npm install --silent

RUN npm install react-scripts@5.0.0 -g --silent

COPY . . 

# CMD echo "Hello to Muhammad Amin from docker"

CMD ["npm", "start"]




