FROM node:latest

WORKDIR './app'

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json .

COPY package-lock.json .

RUN npm install

COPY . . 

# CMD echo "Hello to Muhammad Amin from docker"

CMD ["npm", "start"]




