export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_ERROR = "AUTH_LOGOUT_ERROR";

export const AUTH_ME = "AUTH_ME";
export const AUTH_ME_SUCCESS = "AUTH_ME_SUCCESS";
export const AUTH_ME_ERROR = "AUTH_ME_ERROR";

export const AUTH_SETTING = "AUTH_SETTING";
export const AUTH_SETTING_SUCCESS = "AUTH_SETTING_SUCCESS";
export const AUTH_SETTING_ERROR = "AUTH_SETTING_ERROR";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";


export const GET_TEACHERS = "GET_TEACHERS";
export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
export const GET_TEACHERS_ERROR = "GET_TEACHERS_ERROR";

export const GET_SINGLE_TEACHER = "GET_SINGLE_TEACHER";
export const GET_SINGLE_TEACHER_SUCCESS = "GET_SINGLE_TEACHER_SUCCESS";
export const GET_SINGLE_TEACHER_ERROR = "GET_SINGLE_TEACHER_ERROR";


export const POST_TEACHERS = "POST_TEACHERS";
export const POST_TEACHERS_SUCCESS = "POST_TEACHERS_SUCCESS";
export const POST_TEACHERS_ERROR = "POST_TEACHERS_ERROR";
