export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_ERROR = "AUTH_LOGOUT_ERROR";

export const AUTH_ME = "AUTH_ME";
export const AUTH_ME_SUCCESS = "AUTH_ME_SUCCESS";
export const AUTH_ME_ERROR = "AUTH_ME_ERROR";

export const AUTH_SETTING = "AUTH_SETTING";
export const AUTH_SETTING_SUCCESS = "AUTH_SETTING_SUCCESS";
export const AUTH_SETTING_ERROR = "AUTH_SETTING_ERROR";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";


// teacher
export const GET_TEACHERS = "GET_TEACHERS";
export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
export const GET_TEACHERS_ERROR = "GET_TEACHERS_ERROR";

export const DELETE_TEACHER = "DELETE_TEACHER";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const DELETE_TEACHER_ERROR = "DELETE_TEACHER_ERROR";

export const GET_SINGLE_TEACHER = "GET_SINGLE_TEACHER";
export const GET_SINGLE_TEACHER_SUCCESS = "GET_SINGLE_TEACHER_SUCCESS";
export const GET_SINGLE_TEACHER_ERROR = "GET_SINGLE_TEACHER_ERROR";


export const POST_TEACHERS = "POST_TEACHERS";
export const POST_TEACHERS_SUCCESS = "POST_TEACHERS_SUCCESS";
export const POST_TEACHERS_ERROR = "POST_TEACHERS_ERROR";


export const PUT_TEACHERS = "PUT_TEACHERS";
export const PUT_TEACHERS_SUCCESS = "PUT_TEACHERS_SUCCESS";
export const PUT_TEACHERS_ERROR = "PUT_TEACHERS_ERROR";


// lanugages
export const GET_LANGUAGES = "GET_LANGUAGES";
export const GET_LANGUAGES_ERROR = "GET_LANGUAGES_ERROR";
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS";

export const DELETE_LANGUAGE = "DELETE_LANGUAGE";
export const DELETE_LANGUAGE_SUCCESS = "DELETE_LANGUAGE_SUCCESS";
export const DELETE_LANGUAGE_ERROR = "DELETE_LANGUAGE_ERROR";

export const GET_SINGLE_LANGUAGE = "GET_SINGLE_LANGUAGE";
export const GET_SINGLE_LANGUAGE_ERROR = "GET_SINGLE_LANGUAGE_ERROR";
export const GET_SINGLE_LANGUAGE_SUCCESS = "GET_SINGLE_LANGUAGE_SUCCESS";

export const POST_LANGUAGE = "POST_LANGUAGE";
export const POST_LANGUAGE_ERROR = "POST_LANGUAGE_ERROR";
export const POST_LANGUAGE_SUCCESS = "POST_LANGUAGE_SUCCESS";


// subject


export const GET_SUBJECTS = "GET_SUBJECTS";
export const GET_SUBJECTS_ERROR = "GET_SUBJECTS_ERROR";
export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS";


export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_ERROR = "DELETE_SUBJECT_ERROR";


export const GET_SINGLE_SUBJECT = "GET_SINGLE_SUBJECT";
export const GET_SINGLE_SUBJECT_ERROR = "GET_SINGLE_SUBJECT_ERROR";
export const GET_SINGLE_SUBJECT_SUCCESS = "GET_SINGLE_SUBJECT_SUCCESS";


export const POST_SUBJECT = "POST_SUBJECT";
export const POST_SUBJECT_ERROR = "POST_SUBJECT_ERROR";
export const POST_SUBJECT_SUCCESS = "POST_SUBJECT_SUCCESS";
