export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_ERROR = "AUTH_LOGOUT_ERROR";

export const AUTH_ME = "AUTH_ME";
export const AUTH_ME_SUCCESS = "AUTH_ME_SUCCESS";
export const AUTH_ME_ERROR = "AUTH_ME_ERROR";

export const AUTH_SETTING = "AUTH_SETTING";
export const AUTH_SETTING_SUCCESS = "AUTH_SETTING_SUCCESS";
export const AUTH_SETTING_ERROR = "AUTH_SETTING_ERROR";

// teacher
export const GET_TEACHERS = "GET_TEACHERS";
export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
export const GET_TEACHERS_ERROR = "GET_TEACHERS_ERROR";

export const VIEW_TEACHER = "VIEW_TEACHERS";
export const VIEW_TEACHER_SUCCESS = "VIEW_TEACHERS_SUCCESS";
export const VIEW_TEACHER_ERROR = "VIEW_TEACHERS_ERROR";

export const DELETE_TEACHER = "DELETE_TEACHER";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const DELETE_TEACHER_ERROR = "DELETE_TEACHER_ERROR";

export const GET_SINGLE_TEACHER = "GET_SINGLE_TEACHER";
export const GET_SINGLE_TEACHER_SUCCESS = "GET_SINGLE_TEACHER_SUCCESS";
export const GET_SINGLE_TEACHER_ERROR = "GET_SINGLE_TEACHER_ERROR";


export const POST_TEACHERS = "POST_TEACHERS";
export const POST_TEACHERS_SUCCESS = "POST_TEACHERS_SUCCESS";
export const POST_TEACHERS_ERROR = "POST_TEACHERS_ERROR";


export const CHECK_STUDENT_TEACHER = "CHECK_STUDENT_TEACHER";
export const CHECK_STUDENT_TEACHER_SUCCESS = "CHECK_STUDENT_TEACHER_SUCCESS";
export const CHECK_STUDENT_TEACHER_ERROR = "CHECK_STUDENT_TEACHER_ERROR";


export const PUT_TEACHERS = "PUT_TEACHERS";
export const PUT_TEACHERS_SUCCESS = "PUT_TEACHERS_SUCCESS";
export const PUT_TEACHERS_ERROR = "PUT_TEACHERS_ERROR";


// lanugages
export const GET_LANGUAGES = "GET_LANGUAGES";
export const GET_LANGUAGES_ERROR = "GET_LANGUAGES_ERROR";
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS";

export const DELETE_LANGUAGE = "DELETE_LANGUAGE";
export const DELETE_LANGUAGE_SUCCESS = "DELETE_LANGUAGE_SUCCESS";
export const DELETE_LANGUAGE_ERROR = "DELETE_LANGUAGE_ERROR";

export const GET_SINGLE_LANGUAGE = "GET_SINGLE_LANGUAGE";
export const GET_SINGLE_LANGUAGE_ERROR = "GET_SINGLE_LANGUAGE_ERROR";
export const GET_SINGLE_LANGUAGE_SUCCESS = "GET_SINGLE_LANGUAGE_SUCCESS";

export const POST_LANGUAGE = "POST_LANGUAGE";
export const POST_LANGUAGE_ERROR = "POST_LANGUAGE_ERROR";
export const POST_LANGUAGE_SUCCESS = "POST_LANGUAGE_SUCCESS";


// subject
export const GET_SUBJECTS = "GET_SUBJECTS";
export const GET_SUBJECTS_ERROR = "GET_SUBJECTS_ERROR";
export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS";

export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_ERROR = "DELETE_SUBJECT_ERROR";

export const GET_SINGLE_SUBJECT = "GET_SINGLE_SUBJECT";
export const GET_SINGLE_SUBJECT_ERROR = "GET_SINGLE_SUBJECT_ERROR";
export const GET_SINGLE_SUBJECT_SUCCESS = "GET_SINGLE_SUBJECT_SUCCESS";

export const PUT_SUBJECT = "PUT_SUBJECT";
export const PUT_SUBJECT_ERROR = "PUT_SUBJECT_ERROR";
export const PUT_SUBJECT_SUCCESS = "PUT_SUBJECT_SUCCESS";

export const POST_SUBJECT = "POST_SUBJECT";
export const POST_SUBJECT_ERROR = "POST_SUBJECT_ERROR";
export const POST_SUBJECT_SUCCESS = "POST_SUBJECT_SUCCESS";


// groups

export const GET_GROUPS = "GET_GROUPS";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_ERROR = "GET_GROUPS_ERROR";

export const GET_GROUPS_TEACHER = "GET_GROUPS_TEACHER";
export const GET_GROUPS_TEACHER_SUCCESS = "GET_GROUPS_TEACHER_SUCCESS";
export const GET_GROUPS_TEACHER_ERROR = "GET_GROUPS_TEACHER_ERROR";

export const DELETE_GROUP = "DELETE_GROUP";
export const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";
export const DELETE_GROUP_ERROR = "DELETE_GROUP_ERROR";

export const GET_SINGLE_GROUP = "GET_SINGLE_GROUP";
export const GET_SINGLE_GROUP_SUCCESS = "GET_SINGLE_GROUP_SUCCESS";
export const GET_SINGLE_GROUP_ERROR = "GET_SINGLE_GROUP_ERROR";

export const PUT_GROUP = "PUT_GROUP";
export const PUT_GROUP_SUCCESS = "PUT_GROUP_SUCCESS";
export const PUT_GROUP_ERROR = "PUT_GROUP_ERROR";

export const POST_GROUP = "POST_GROUP";
export const POST_GROUP_SUCCESS = "POST_GROUP_SUCCESS";
export const POST_GROUP_ERROR = "POST_GROUP_ERROR";

export const GET_TEACHER_GROUPS = "GET_TEACHER_GROUPS";
export const GET_TEACHER_GROUPS_SUCCESS = "GET_TEACHER_GROUPS_SUCCESS";
export const GET_TEACHER_GROUPS_ERROR = "GET_TEACHER_GROUPS_ERROR";



// Student


export const GET_STUDENTS = "GET_STUDENTS";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const GET_STUDENTS_ERROR = "GET_STUDENTS_ERROR";

export const GET_STUDENTS_GROUP = "GET_STUDENTS_GROUP";
export const GET_STUDENTS_GROUP_ERROR = "GET_STUDENTS_GROUP_ERROR";
export const GET_STUDENTS_GROUP_SUCCESS = "GET_STUDENTS_GROUP_SUCCESS";

export const GET_NEW_STUDENTS = "GET_NEW_STUDENTS";
export const GET_NEW_STUDENTS_SUCCESS = "GET_NEW_STUDENTS_SUCCESS";
export const GET_NEW_STUDENTS_ERROR = "GET_NEW_STUDENTS_ERROR";

export const DELETE_STUDENT = "DELETE_STUDENT";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_ERROR = "DELETE_STUDENT_ERROR";

export const GET_SINGLE_STUDENT = "GET_SINGLE_STUDENT";
export const GET_SINGLE_STUDENT_SUCCESS = "GET_SINGLE_STUDENT_SUCCESS";
export const GET_SINGLE_STUDENT_ERROR = "GET_SINGLE_STUDENT_ERROR";

export const POST_STUDENT_GROUP = "POST_STUDENT_GROUP";
export const POST_STUDENT_GROUP_SUCCESS = "POST_STUDENT_GROUP_SUCCESS";
export const POST_STUDENT_GROUP_ERROR = "POST_STUDENT_GROUP_ERROR";


export const GET_SINGLE_GROUP_STUDENT = "GET_SINGLE_GROUP_STUDENT";
export const GET_SINGLE_GROUP_STUDENT_SUCCESS = "GET_SINGLE_GROUP_STUDENT_SUCCESS";
export const GET_SINGLE_GROUP_STUDENT_ERROR = "GET_SINGLE_GROUP_STUDENT_ERROR";


export const POST_STUDENT = "POST_STUDENT";
export const POST_STUDENT_SUCCESS = "POST_STUDENT_SUCCESS";
export const POST_STUDENT_ERROR = "POST_STUDENT_ERROR";


export const POST_STUDENT_LOGIN = "POST_STUDENT_LOGIN";
export const POST_STUDENT_LOGIN_ERROR = "POST_STUDENT_LOGIN_ERROR";
export const POST_STUDENT_LOGIN_SUCCESS = "POST_STUDENT_LOGIN_SUCCESS";

export const PUT_STUDENT = "PUT_STUDENT";
export const PUT_STUDENT_SUCCESS = "PUT_STUDENT_SUCCESS";
export const PUT_STUDENT_ERROR = "PUT_STUDENT_ERROR";

export const STUDENT_PAYMENT = "STUDENT_PAYMENT";
export const STUDENT_PAYMENT_SUCCESS = "STUDENT_PAYMENT_SUCCESS";
export const STUDENT_PAYMENT_ERROR = "STUDENT_PAYMENT_ERROR";


// statistic
export const GET_STATISTICS = "GET_STATISTICS";
export const GET_STATISTICS_SUCCESS = "GET_STATISTICS_SUCCESS";
export const GET_STATISTICS_ERROR = "GET_STATISTICS_ERROR";

export const GET_STATISTICS_CHART = "GET_STATISTICS_CHART";
export const GET_STATISTICS_CHART_SUCCESS = "GET_STATISTICS_CHART_SUCCESS";
export const GET_STATISTICS_CHART_ERROR = "GET_STATISTICS_CHART_ERROR";


// Super Admin
export const GET_ALL_USERS = "GET_STATISTICS_CHART";
export const GET_ALL_USERS_SUCCESS = "GET_STATISTICS_CHART_SUCCESS";
export const GET_ALL_USERS_ERROR = "GET_STATISTICS_CHART_ERROR";

export const GET_USERS_AUTH = "GET_USERS_AUTH";
export const GET_USERS_AUTH_SUCCESS = "GET_USERS_AUTH_SUCCESS";
export const GET_USERS_AUTH_ERROR = "GET_USERS_AUTH_ERROR";

